### ISSUE TITLE
Nice work, but when i wanna run this code there is a mistake.

### ISSUE THREAD

**Issue by 404hasbeenfound** [longcw/MOTDT#17]
Traceback (most recent call last):
  File "eval_mot.py", line 2, in <module>
    import cv2
ImportError: /lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /home/adminroot/anaconda3/envs/zmh/lib/libpng16.so.16)
(zmh) adminroot@adminroot:~/zmh/MOTDT-master$ pip install zlib
Collecting zlib
  Could not find a version that satisfies the requirement zlib (from versions: )
No matching distribution found for zlib

i try pip install ZLIB, but it fails, i donot know why, would you have some suggestions?

**Comment by 404hasbeenfound** [comment]
when i follow your steps one by one, but when i run 'python eval_mot.py' there is a mistake like:

(zmh) adminroot@adminroot:~/zmh/MOTDT-master$ python eval_mot.py
Traceback (most recent call last):
  File "eval_mot.py", line 158, in <module>
    show_image=False)
  File "eval_mot.py", line 93, in main
    mkdirs(result_root)
  File "eval_mot.py", line 17, in mkdirs
    os.makedirs(path)
  File "/home/adminroot/anaconda3/envs/zmh/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/home/adminroot/anaconda3/envs/zmh/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/home/adminroot/anaconda3/envs/zmh/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  [Previous line repeated 2 more times]
  File "/home/adminroot/anaconda3/envs/zmh/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/data'

then i think that it havn't
