### ISSUE TITLE
when i follow your steps one by one, but when i run 'python eval_mot.py' there is a mistake like:

### ISSUE THREAD

**Issue by 404hasbeenfound** [longcw/MOTDT#18]
(zmh) adminroot@adminroot:~/zmh/MOTDT-master$ python eval_mot.py
Traceback (most recent call last):
  File "eval_mot.py", line 158, in <module>
    show_image=False)
  File "eval_mot.py", line 93, in main
    mkdirs(result_root)
  File "eval_mot.py", line 17, in mkdirs
    os.makedirs(path)
  File "/home/adminroot/anaconda3/envs/zmh/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/home/adminroot/anaconda3/envs/zmh/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/home/adminroot/anaconda3/envs/zmh/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  [Previous line repeated 2 more times]
  File "/home/adminroot/anaconda3/envs/zmh/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/data'

then i think that it havn't

_Originally posted by @404hasbeenfound in https://github.com/longcw/MOTDT/issue_comments#issuecomment-448631912_

**Comment by 404hasbeenfound** [comment]
use sudo python command
