### ISSUE TITLE
when run sh make.sh,i got troubles:

### ISSUE THREAD

**Issue by feixiaoyu2223** [longcw/MOTDT#33]
Traceback (most recent call last):   File "build.py", line 29, in <module>     extra_objects=extra_objects   File "/home/fly/anaconda3/envs/fly/lib/python3.6/site-packages/setuptools/__init__.py", line 127, in __init__     _Command.__init__(self, dist)   File "/home/fly/anaconda3/envs/fly/lib/python3.6/distutils/cmd.py", line 57, in __init__     raise TypeError("dist must be a Distribution instance") TypeError: dist must be a Distribution instance.
Look forward to your reply,thank you

**Comment by Hackerlil** [comment]
就是pytorch的版本问题，我创建了一个新的环境按照requirements，用的是pytorch 0.4.1然后就没问题了

**Comment by feixiaoyu2223** [comment]
你好，我的pytorch版本是0.4.1，在服务器上跑没有问题，自己笔记本上一样的环境就出现了bug，这是为什么呀


------------------




 




------------------ 原始邮件 ------------------
发件人: "Jakuid"<notifications@github.com>;
发送时间: 2019年5月17日(星期五) 晚上8:31
收件人: "longcw/MOTDT"<MOTDT@noreply.github.com>;
抄送: "Fred.Fly"<441275397@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [longcw/MOTDT] when run sh make.sh,i got troubles: (#33)




就是pytorch的版本问题，我创建了一个新的环境按照requirements，用的是pytorch 0.4.1然后就没问题了
